### PR TITLE
Tweak collision detection

### PR DESCRIPTION
**Pull request by RobLoach**
This checks ball collisions only if the ball is on the correct side of the court, rather then checking both at the same time.

### CODE REVIEW

**Comment by Alcaro** [comment]
Does that make any difference in behavior or performance? If no, I prefer the old version, it's easier to read.

**Comment by RobLoach** [comment]
Was running into some strange cases where the ball would jump back and forth if caught inside the paddle. It would jump back and forth, and then go the incorrect direction. Having a check to see which paddle it is to collide with seems to fix it.

Added some code comments to help clarify the code.

**Comment by Alcaro** [comment]
Something tells me that check won't fix that bug.

Check the movement direction instead.

**Comment by RobLoach** [comment]
Agreed, something is messed with the collision/movement logic.

**Pull request closed without merging**
